SCR_MapConfig {
 m_iMapMode EDITOR
 m_LayersConfig SCR_MapLayersBase "{58C89E71EB05BD95}" : "{3CAC09C3E89190F7}Configs/Map/MapLayersDefault.conf" {
 }
 m_MapPropsConfig SCR_MapPropsBase "{58C89E75E0624E84}" : "{AF65563F653FED68}Configs/Map/MapPropsDefault.conf" {
 }
 m_aModules {
  SCR_MapCursorModule "{5510976090640513}" : "{5E40C9235FDA4430}Configs/Map/Prefabs/MapCursorModuleDef.conf" {
   m_bIsCursorCenteredOnOpen 0
  }
  SCR_MapSelectionModule "{697318201A39E68E}" {
  }
 }
 m_aUIComponents {
  SCR_MapCampaignUI "{697318201A39DB7F}" {
  }
  SCR_MapDebugUI "{697318201A39DB7B}" {
  }
  GME_GMEditorMapOverlayUIComponent {
  }
 }
 m_bEnableLegendScale 1
 m_DescriptorVisibilityConfig SCR_MapDescriptorVisibilityBase "{58C8DDC940756CA1}" : "{4FFDB559B60FC7BC}Configs/Map/MapDescriptorVisibilityDefault.conf" {
 }
 m_DescriptorDefaultsConfig SCR_MapDescriptorDefaults "{58C89E629DF577A5}" : "{FF6B20825D4A566C}Configs/Map/MapDescriptorDefaults.conf" {
 }
}
